-- Website Roast AI baseline schema
-- Run in Supabase SQL editor (or as migration) before enabling production persistence.

create extension if not exists pgcrypto;

create table if not exists public.roast_reports (
  id uuid primary key,
  url text not null,
  user_id uuid null references auth.users(id) on delete set null,
  scrape_hash text not null,
  scraped jsonb not null,
  scoring jsonb not null,
  roast jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.roast_reports
  add column if not exists user_id uuid null references auth.users(id) on delete set null;

create unique index if not exists roast_reports_url_scrape_hash_key
  on public.roast_reports (url, scrape_hash);

create index if not exists roast_reports_created_at_idx
  on public.roast_reports (created_at desc);
create index if not exists roast_reports_user_id_idx
  on public.roast_reports (user_id, created_at desc);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  name text not null check (
    name in (
      'landing_view',
      'roast_submit',
      'roast_success',
      'roast_error',
      'result_view'
    )
  ),
  session_id text not null,
  variant text null check (variant in ('A', 'B')),
  metadata jsonb null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_name_idx
  on public.analytics_events (name);

create table if not exists public.roast_feedback (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.roast_reports(id) on delete cascade,
  user_id uuid null references auth.users(id) on delete set null,
  session_id text not null,
  url text not null,
  score_at_review numeric(3,1) not null,
  score_accuracy smallint not null check (score_accuracy between 1 and 5),
  tone_accuracy text not null check (tone_accuracy in ('too_soft', 'balanced', 'too_harsh')),
  notes text null,
  created_at timestamptz not null default now()
);

alter table public.roast_feedback
  add column if not exists user_id uuid null references auth.users(id) on delete set null;

create unique index if not exists roast_feedback_report_session_key
  on public.roast_feedback (report_id, session_id);

create index if not exists roast_feedback_created_at_idx
  on public.roast_feedback (created_at desc);

create index if not exists roast_feedback_tone_accuracy_idx
  on public.roast_feedback (tone_accuracy);
create index if not exists roast_feedback_user_id_idx
  on public.roast_feedback (user_id, created_at desc);
